### ISSUE TITLE
How do I dynamically add or delete items?

### ISSUE THREAD

**Issue by tilongzs** [Palm1r/QmlTreeViewExample#5]
I tried to add a function in TreeModel, called by a button, but it doesn't work.Thanks.
`Q_INVOKABLE void adddata();`
```
void TreeModel::adddata()
{
    auto child = new TreeItem("testChild");
    addTreeItem(_rootItem.get(), child);
}
```

_Originally posted by @tilongzs in https://github.com/Palm1r/QmlTreeViewExample/discussions/4_

**Comment by Palm1r** [comment]
I am working on new tree item and model, I will add dynamic add / remove

**Comment by Palm1r** [comment]
I reworked tree item. model and adding new items. Please check this in last commit. I will continue work on my tree in the future.  I want add work with select index and canFetch.

**Comment by tilongzs** [comment]
Thank you. I'll keep an eye on it.
